on:
  workflow_dispatch:
    inputs:
      Slots:
        type: string
        required: true
      Symbols:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'old'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build --configuration Debug
      - run: dotnet run --configuration Debug -- ${{inputs.Slots}} -- ${{inputs.Symbols}}
      - run: dotnet build --configuration Release
      - run: dotnet run --configuration Release -- ${{inputs.Slots}} -- ${{inputs.Symbols}} > output.txt
      - run: cat output.txt
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.txt
