on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        required: true
        options:
          - linux
          - win
      arch:
        type: choice
        required: true
        options:
          - x64
          - arm64

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet publish -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained --framework net8.0 --runtime ${{inputs.os}}-${{inputs.arch}}
      - uses: actions/upload-artifact@v3
        with:
          name: Nerdle-${{inputs.os}}-${{inputs.arch}}
          path: bin/Release/net8.0/${{inputs.os}}-${{inputs.arch}}/publish
          retention-days: 1
